# Generated by Django 4.1.6 on 2023-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_package_user_request_made_user_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_apps',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
