# Generated by Django 4.1.6 on 2023-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_counts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('longtitute', models.CharField(max_length=120)),
                ('lattitute', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='counts',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='base.dailylocations'),
        ),
    ]
